"""English versions of the catalogue, for bilingual study participants."""

DESCRIPTIONS_EN = {
    "orphan-sponsorship-monthly": "A monthly sponsorship covering an orphan's basic needs: food, clothing, healthcare and schooling, giving them stability as they grow up.",
    "orphan-eid-clothing": "New Eid clothes for orphans, so they share the joy of the occasion like other children.",
    "orphan-housing-furnish": "Furniture and essential appliances for orphan families, for a dignified and safe home.",
    "orphan-education-fund": "University tuition and study supplies for high-achieving orphans to complete higher education.",
    "orphan-psych-support": "Counselling and behavioural support programmes that help orphans cope with loss and build confidence.",
    "orphan-summer-club": "Recreational and educational summer activities that develop orphans' skills during the school holidays.",
    "school-bags-students": "School bags and supplies for children from families in need at the start of the school year.",
    "tuition-support": "Paying overdue school fees for students at risk of losing their place.",
    "quran-memorization": "Running Quran memorisation circles: teachers' stipends, copies of the Quran and teaching materials.",
    "digital-devices-students": "Tablets and internet subscriptions so students in need can keep learning remotely.",
    "literacy-adults": "Reading and writing classes for adults, giving them more independence in daily life.",
    "vocational-training": "Vocational training that leads to employment, moving families from aid to self-reliance.",
    "cancer-treatment-support": "Covering chemotherapy, medication and tests for cancer patients who cannot afford them.",
    "dialysis-machines": "Modern dialysis machines for kidney units, reducing waiting lists in remote areas.",
    "medical-escort": "Transport and temporary housing for patients and their companions travelling to medical cities.",
    "prosthetics-fund": "Prosthetic limbs and physical rehabilitation sessions for amputees.",
    "smoking-awareness": "Awareness campaigns and quit-smoking clinics aimed at young people and school students.",
    "mother-child-care": "Regular check-ups and care supplies for mothers and newborns in families in need.",
    "home-maintenance": "Repairing unsafe homes, fixing leaks and electrical faults to protect the families living in them.",
    "rent-support": "Paying overdue rent for families at risk of eviction, keeping them housed.",
    "home-appliances": "Washing machines, fridges and air conditioners for families in need, easing daily living.",
    "build-family-home": "Building complete housing units for families without a home, handed over ready to live in.",
    "furniture-bank": "Collecting and refurbishing used furniture and redistributing it to families in need instead of discarding it.",
    "cooling-units-summer": "Air conditioners for families in need in very hot areas during the summer months.",
    "mosque-construction": "Building new mosques in neighbourhoods and villages without a nearby place of prayer.",
    "mosque-maintenance": "Maintaining washrooms, air conditioning, carpets and lighting in existing mosques.",
    "mosque-water-coolers": "Installing and maintaining drinking-water coolers in mosques and prayer areas.",
    "mosque-carpets": "Carpeting mosques and replacing worn-out carpets.",
    "quran-copies": "Printing copies of the Quran in several sizes and distributing them to mosques and Quran schools.",
    "imam-support": "Stipends and living support for imams and muezzins in remote villages.",
    "emergency-relief-fund": "Rapid response to disasters and crises with shelter, food and medical supplies within hours.",
    "flood-response": "Shelter and provisions for families affected by floods, and replacing lost furniture and supplies.",
    "winter-blankets": "Blankets, winter clothing and heaters for families in cold areas.",
    "food-baskets": "A monthly food basket of staples sufficient for a family of five.",
    "water-wells": "Drilling wells and fitting pumps to provide drinking water for deprived villages.",
    "refugee-support": "Shelter, food and education support for families displaced by conflict.",
    "wheelchairs": "Manual and electric wheelchairs for people with mobility impairments.",
    "hearing-aids": "Hearing aids and cochlear implants for children with hearing loss, with speech therapy.",
    "autism-center": "Running a specialised centre for children with autism and training their families.",
    "accessible-home-mod": "Adapting homes with ramps, grab rails and accessible bathrooms for people with disabilities.",
    "braille-library": "Producing Braille and audio books and distributing them to blind readers and students.",
    "disability-employment": "Training people with disabilities and connecting them with suitable jobs.",
    "plant-trees-desert": "Planting and caring for native trees to fight desertification and improve air quality.",
    "beach-cleanup": "Volunteer campaigns to clean beaches and nature reserves and sort the collected waste.",
    "food-waste-reduction": "Collecting surplus food from events and restaurants and safely redistributing it to people in need.",
    "solar-panels-villages": "Solar power systems for remote villages to run lighting, pumps and schools.",
    "recycling-schools": "Awareness programmes and sorting stations that build a recycling culture in schools.",
    "wildlife-protection": "Supporting breeding and reintroduction programmes for endangered species in reserves.",
    "productive-families": "Funding, training and equipment for home-based family businesses to become sustainable.",
    "marriage-support": "Helping young people from families in need with the costs of getting married.",
    "debt-relief-gharimin": "Paying the debts of insolvent debtors in prison so they can return to their families.",
    "widows-support": "Monthly support and empowerment programmes for widows and divorced women supporting their families.",
    "elderly-care": "Home visits, healthcare and daily supplies for elderly people living without support.",
    "family-counselling": "",
    "family-counseling": "Family counselling and reconciliation services that help keep families together.",
    "iftar-saem": "Iftar meals in mosques and tents for people fasting throughout Ramadan.",
    "zakat-alfitr": "Paying Zakat al-Fitr on your behalf and distributing it to those entitled before the Eid prayer.",
    "udhiyah-sacrifice": "Performing the Eid sacrifice and distributing fresh meat to families in need at home and abroad.",
    "ramadan-food-basket": "A Ramadan food basket of staples to last a family the whole month.",
    "hajj-pilgrim-services": "Water, meals and guidance for pilgrims at the holy sites.",
    "eid-gifts-children": "Eid gifts for children from families in need and children in hospital.",
    "general-sadaqah": "General charity directed to the most pressing needs on the ground at the time.",
    "sadaqah-jariyah": "Projects with lasting benefit whose reward continues after the giver's death: wells, Qurans, public facilities.",
    "zakat-almaal": "Calculating your zakat and distributing it to its eight legitimate categories of recipients through verified charities.",
    "volunteer-programs": "Training and equipping volunteers and running community initiatives across regions.",
    "community-parks": "Developing parks, playgrounds and public facilities in underserved neighbourhoods.",
    "emergency-medical-fund": "Urgent intervention for critical humanitarian cases that cannot wait, such as patients and people affected by accidents.",
    "waqf-education": "An investment endowment whose returns permanently fund scholarships and support schools.",
    "waqf-health": "An endowment whose returns fund treatment for patients in need and equip health centres.",
    "waqf-orphans": "A permanent endowment whose returns fund orphan sponsorships every year without touching the principal.",
    "waqf-mosques": "An endowment that sustainably covers mosques' running costs: electricity, water and carpets.",
    "waqf-water": "An endowment that operates and maintains wells and desalination units to supply villages with water permanently.",
    "waqf-quran": "An endowment whose returns print copies of the Quran every year for mosques and Quran schools.",
}
DESCRIPTIONS_EN.pop("family-counselling")

UNITS_EN = {
    "orphan-sponsorship-monthly": "one month of orphan sponsorship", "orphan-eid-clothing": "Eid clothes for one orphan",
    "orphan-housing-furnish": "furnishing one room for an orphan family", "orphan-education-fund": "one university semester for an orphan",
    "orphan-psych-support": "one counselling session", "orphan-summer-club": "one orphan's summer-club place",
    "school-bags-students": "one complete school bag", "tuition-support": "one semester's fees for a student",
    "quran-memorization": "one month's stipend for a Quran teacher", "digital-devices-students": "a tablet with a year of internet",
    "literacy-adults": "one place in a literacy course", "vocational-training": "one trainee's vocational programme",
    "cancer-treatment-support": "one chemotherapy session", "dialysis-machines": "one dialysis session",
    "medical-escort": "one treatment trip with lodging for a patient and companion", "prosthetics-fund": "one prosthetic limb with rehabilitation",
    "smoking-awareness": "one school awareness campaign", "mother-child-care": "a care package for a mother and newborn",
    "home-maintenance": "repairing one average home", "rent-support": "one month's rent for a family",
    "home-appliances": "one essential home appliance", "build-family-home": "one complete housing unit",
    "furniture-bank": "refurbishing and delivering one piece of furniture", "cooling-units-summer": "one air conditioner, installed",
    "mosque-construction": "one square metre of a mosque", "mosque-maintenance": "one routine mosque maintenance",
    "mosque-water-coolers": "a water cooler with a year of maintenance", "mosque-carpets": "one square metre of carpet",
    "quran-copies": "one copy of the Quran", "imam-support": "one month's stipend for an imam",
    "emergency-relief-fund": "one emergency relief kit for a family", "flood-response": "one week of shelter for an affected family",
    "winter-blankets": "one winter kit for a family", "food-baskets": "one monthly food basket for a family",
    "water-wells": "one well with a pump", "refugee-support": "one month of support for a displaced family",
    "wheelchairs": "one manual wheelchair", "hearing-aids": "one hearing aid",
    "autism-center": "one month of therapy for a child", "accessible-home-mod": "one accessible bathroom",
    "braille-library": "one Braille book", "disability-employment": "one job-readiness programme",
    "plant-trees-desert": "one native tree with a year of watering", "beach-cleanup": "one beach clean-up campaign",
    "food-waste-reduction": "one surplus meal redistributed", "solar-panels-villages": "one home solar system",
    "recycling-schools": "one school sorting station", "wildlife-protection": "one month of care for an endangered animal",
    "productive-families": "equipment for one family business", "marriage-support": "a contribution to one wedding",
    "debt-relief-gharimin": "paying one debtor's debt (average)", "widows-support": "one month of support for a widow",
    "elderly-care": "one home-care visit to an elderly person", "family-counseling": "one family counselling session",
    "iftar-saem": "one iftar meal", "zakat-alfitr": "Zakat al-Fitr for one person", "udhiyah-sacrifice": "one sacrifice",
    "ramadan-food-basket": "one Ramadan basket for a family", "hajj-pilgrim-services": "a meal and water for one pilgrim",
    "eid-gifts-children": "one Eid gift for a child", "general-sadaqah": "one general contribution",
    "sadaqah-jariyah": "one share in an ongoing project", "zakat-almaal": "one month of zakat support for a family",
    "volunteer-programs": "equipping one volunteer", "community-parks": "one square metre of neighbourhood park",
    "emergency-medical-fund": "one urgent medical intervention (average)",
    "waqf-education": "one endowment share", "waqf-health": "one endowment share", "waqf-orphans": "one endowment share",
    "waqf-mosques": "one endowment share", "waqf-water": "one endowment share", "waqf-quran": "one endowment share",
}

CHARITIES_EN = {
    "athar": ("Al-Athar Charitable Society", "A general charity running food aid and family support programmes in several regions."),
    "rifd": ("Rifd Orphan Care Society", "Specialises in sponsoring orphans and supporting their education and wellbeing until independence."),
    "suqya": ("Suqya Endowment Foundation", "An endowment foundation whose returns fund water provision and mosque upkeep."),
    "namaa": ("Namaa Family Development Society", "Helps families become financially independent and resolves housing and debt problems."),
    "shifa": ("Shifa Patient Support Society", "Covers treatment and medical transport costs for patients who cannot afford them."),
    "buyut": ("Buyut Al-Khair Housing Society", "Builds, repairs and furnishes homes for families in need."),
    "amal": ("Amal Society for People with Disabilities", "Provides assistive devices, rehabilitation and employment for people with disabilities."),
    "ghiras": ("Ghiras Environmental Society", "A young environmental charity working on tree planting, food waste and clean energy."),
    "manara": ("Manara Quran Education Society", "Oversees Quran memorisation circles, Quran printing and support for imams."),
    "awn": ("Awn Relief Society", "Rapid disaster response plus seasonal programmes in Ramadan and winter."),
    "midad": ("Midad Education Society", "Supports students in need with fees, devices and vocational training."),
    "wafa": ("Wafa Elderly Care Society", "Home and health care for elderly people with no one to support them."),
}

REGIONS_EN = {
    "الرياض": "Riyadh", "مكة المكرمة": "Makkah", "المدينة المنورة": "Madinah", "المنطقة الشرقية": "Eastern Province",
    "عسير": "Asir", "القصيم": "Qassim", "جازان": "Jazan", "تبوك": "Tabuk", "حائل": "Hail", "نجران": "Najran",
    "الباحة": "Al-Baha", "الجوف": "Al-Jouf",
}

ZAKAT_CATEGORY_EN = {"الفقراء والمساكين": "the poor and the needy", "الغارمين": "those in debt"}

UPDATE_TEMPLATES_EN = [
    "A new tranche of donations was disbursed and phase {phase} of the project was carried out.",
    "The charity's field team visited {region} to verify implementation.",
    "The number of registered beneficiaries has reached {n}.",
    "The quarterly progress report was published and can be requested from the charity.",
    "The list of eligible beneficiaries was updated after reviewing new cases.",
]
